CREATE TABLE SQLSchedulerJobs (
  JOBID          VARCHAR(255)    NOT NULL PRIMARY KEY,
  STARTTIME    INTEGER    NOT NULL,
  FREQ         INTEGER    NOT NULL,
  CATEGORY        VARCHAR (255) NOT NULL,
  TASKS        TEXT
);